"""empty message

Revision ID: 6dc7dc0e410b
Revises: 
Create Date: 2024-01-11 15:15:17.409306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc7dc0e410b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=255), nullable=False),
    sa.Column('airline', sa.String(length=255), nullable=False),
    sa.Column('registration', sa.String(length=255), nullable=False),
    sa.Column('departure_airport', sa.String(length=255), nullable=False),
    sa.Column('arrival_airport', sa.String(length=255), nullable=False),
    sa.Column('aircraft_type', sa.String(length=255), nullable=False),
    sa.Column('departure_delay', sa.Integer(), nullable=False),
    sa.Column('aircraft_cleanliness', sa.Integer(), nullable=False),
    sa.Column('friendliness', sa.Integer(), nullable=False),
    sa.Column('entertainment_quality', sa.Integer(), nullable=False),
    sa.Column('food_quality', sa.Integer(), nullable=False),
    sa.Column('user_friendliness', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
